version: "3"

services:
  dashboard:
    container_name: dashboard
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DASHBOARD_PORT_REDIRECT_FROM_SYS}:${PORT_RUN_DASHBOARD}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SASS_PATH=node_modules:src
    command: npm run start --inspect
    stdin_open: true
